### ISSUE TITLE
Asynchronous calls with libcurl-multi

### ISSUE THREAD

**Issue by valdemon** [varnish/libvmod-curl#19]
Hi,

as you've suggested in #14 comment i likely will give the libcurl-multi a try in this subject. 
My use case is a kind of obvious - fire-and-forget (as you noticed), without waiting for the response in the Varnish request thread. 
The solution i've proposed in #14 would do for me, however I have some issues with it at a very high load conditions. That's why I'm ready to get the libcurl-multi into play.
Could you please describe any other use case (different than the fire-and-forget) for the asynchronous calls from the VCL perspective, that we'd have a common understanding of the goal?

Best regards,

Waldek

**Comment by mbgrydeland** [comment]
Closing this issue - see comment in pull request.
