### ISSUE TITLE
Segfault when using mod in varnish 4 backend

### ISSUE THREAD

**Issue by jschwertfeger** [varnish/libvmod-curl#23]
Hi there,

I am getting a segfault in the varnish child (dies with signal 11) when using the curl module in any of the two backend subroutines (`vcl_backend_fetch` or `vcl_backend_response`). The issues seems to occur at the module initialization phase already because even a `curl.set_timeout(10)` call triggers it. I am guessing it has to do with the client/backend separation that was introduced in varnish 4. Here is a very simple VCL to reproduce the bug:

```
vcl 4.0;

import curl;

backend default {
    .host = "127.0.0.1";
    .port = "8080";
}

sub vcl_backend_fetch {
  curl.set_timeout(10);
}
```

Any simple fix?

-Jonas

**Comment by aondio** [comment]
For varnish 4.0 please use branch 4.0 which contains a workaround for this issue.
For varnish 4.1 please use branch 4.1 where PRIV_TASK has been used to avoid this problem.
