### ISSUE TITLE
Varnish 4.0 compatibility and include/varnishapi.h

### ISSUE THREAD

**Issue by dinesh-nallaparaju** [varnish/libvmod-curl#24]
Hi,

I'm getting below error while compiling libvmod-curl with Varnish 4.0. Can you let me know if I'm doing something wrong?

checking for /apps/git/workspace/Varnish-Cache/include/varnishapi.h... no
configure: error: in `/apps/git/workspace/libvmod-curl':
configure: error: "/apps/git/workspace/Varnish-Cache" is not a Varnish source directory
See `config.log' for more details.

Thanks,
Dinesh

**Comment by fgsch** [comment]
Are you using the master branch?

**Comment by dinesh-nallaparaju** [comment]
Yes, I'm using the master branch.

**Comment by fgsch** [comment]
Please check again. The configure script in master will not check for varnishapi.h and the Varnish source directory is neither needed nor mentioned anywhere.

**Comment by dinesh-nallaparaju** [comment]
Thanks. I was able to resolve the issue by pointing to correct master branch.
Appreciate your help !!

**Comment by dinesh-nallaparaju** [comment]
I have one more question. Is the code from master branch production ready or do we need to wait for any branch or tag to be created?

**Comment by fgsch** [comment]
It should be fine to use this in prod.

I will close the ticket now.
