### ISSUE TITLE
Requirements and Compatibility

### ISSUE THREAD

**Issue by behdadk** [varnish/libvmod-curl#28]
Hello, 

I'm trying to compile the module against Varnish 4.0.3 (Centos 7) and I'm not successfull. That would be great to include compatible Varnish and libcurl versions in Readme. 

Regards.

**Comment by aondio** [comment]
Hi,
what kind if problem are you encountering?

**Comment by vorlock** [comment]
I'm having the same issue but on centos6.6, below is the `make` output

```
make  all-recursive
make[1]: Entering directory `/root/tmp/varnish-4.0.3/lib/libvmod-curl'
Making all in src
make[2]: Entering directory `/root/tmp/varnish-4.0.3/lib/libvmod-curl/src'
../src/vmod_curl.vcc
make[2]: execvp: ../src/vmod_curl.vcc: Permission denied
make[2]: *** [vcc_if.c] Error 127
make[2]: Leaving directory `/root/tmp/varnish-4.0.3/lib/libvmod-curl/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tmp/varnish-4.0.3/lib/libvmod-curl'
make: *** [all] Error 2
```

whole build process is running on VM

**Comment by aondio** [comment]
Hi vorlock,
do you mind opening another issue here on github where reporting your problem?
Please, also report which branch of the vmod you are using.

**Comment by vorlock** [comment]
Hello @aondio done as requested, issue #29 has been created.
