### ISSUE TITLE
Compile  source code package error  no varnishapi.h

### ISSUE THREAD

**Issue by yichunlan99** [varnish/libvmod-curl#31]
I use varnish version is 4.1.0,libvmod-cur version is 4.1.i try compile ,libvmod-cur ,but error no varnishapi.h

checking for python2.7... python2.7
checking for /usr/local/src/varnish-4.1.0/include/varnishapi.h... no
configure: error: in `/usr/local/src/libvmod-curl3':
configure: error: "/usr/local/src/varnish-4.1.0" is not a Varnish source directory

**Comment by fgsch** [comment]
Are you building Varnish yourself or using packages?
If it's the latter you are missing the dev package, libvarnishapi-dev in Debian/Ubuntu or varnish-libs-devel in CentOS/RedHat.

**Comment by yichunlan99** [comment]
Problem has been done, the method is as follows
export  PKG_CONFIG_PATH=$VARNISH_HOME/lib/pkgconfig/

**Comment by daghf** [comment]
TODO: docfix this
