### ISSUE TITLE
src/tests/test02.vtc fails on el5 and el6

### ISSUE THREAD

**Issue by ingvarha** [varnish/libvmod-curl#36]
src/tests/test02.vtc fails on el5 and el6. 

$ /usr/bin/varnishtest -vvv -Dvarnishd="/usr/sbin/varnishd -j none" -Dvmod_topbuild=/home/ingvar/rpmbuild/BUILD/libvmod-curl-1.0.3 ../src/tests/test02.vtc

output attached.

Ingvar

[test02.vtc.log.txt](https://github.com/varnish/libvmod-curl/files/257881/test02.vtc.log.txt)

**Comment by fgsch** [comment]
Can you share the libcurl versions in each case?

**Comment by nigoroll** [comment]
irc discussion with some insights

> 10:48:19) slink: @fgsch :
> (10:48:19) slink: ***  l1    1.4 waitfor| expect * = Timestamp "curl:end: \\S+ 0\\.2\\d+ 0\\.\\d+"
> (10:48:19) slink: but:
> (10:48:19) slink: **** v1    1.5 vsl|       1001 Timestamp       c curl:end: 1462904437.283417 1.002007 0.000208

So clearly the issue here is that libcurl does not respect the sub-second timeout: We set a timeout of 200ms and it only times out after 1s.

> 
> (11:05:16) slink: ingvar looks like the libcurl (or something else on that system) does not support sub-second timeouts. https://curl.haxx.se/mail/lib-2010-05/0147.html -- I wonder if we really should work around this in the vmod
> (11:05:30) slink: do you see a chance to update libcurl?
> (11:06:58) slink: btw I am not saying that the issue referred to by the email is the actual issue, just makes it obvious that libcurl is the culprit
> (11:07:23) slink: the vsl log is very clear about this: We set a timeout of 200ms, but it only times out after 1s
> (11:07:37) scn: fgs looked into it, i think he found that there were some system components that depended on it
> (11:07:46) scn: and as such upgrading it would be rather high risk
> (11:08:50) slink: so would the solution be to have a newer version libcurl in a separate package?
> (11:09:22) scn: upgrading libcurl means that the other components also use the upgraded one.
> (11:09:29) scn: static link would work.
> (11:09:35) slink: rename the .so?
> (11:09:50) scn: but i think fgs' has a handle on this, really.
> (11:10:02) slink: ok, I'll leave it with him.
> ...
> (11:10:34) scn: i'm confused though, because our internal ticket on this said illisec timers from 7.16.2 and my el6 has 7.19.7
> (11:10:56) scn: so el5 issue only. i don't care much about el5. :)

**Comment by ingvarha** [comment]
el6 has curl-7.19.7
el5 has curl-7.15.5

Ingvar

**Comment by fgsch** [comment]
The problem is that old libcurl versions are broken wrt timeouts.  There is not much we can do about that. 

I can revert the changes, or we can bite the bullet which probably means remove the tests in the broken platforms or ignore the error. Considering that the version on el6 is more than 6 years old I'm more inclined to the latter.

**Comment by lkarsten** [comment]
EL6 is a supported platform and will still be it for a couple of years. We must be able to ship vmod-curl on it. Can the test case be more lenient, or some autoconf magic done to exclude it from the list of tests if running on el6?

**Comment by fgsch** [comment]
I will move the specific (read broken on el6) tests to a new test.
This can be rm'd in the spec before make check runs.

Is that acceptable?

**Comment by fgsch** [comment]
Done.  You need to remove src/tests/test11.vtc on el6.

If this is not acceptable let me know and I will add all the foo to configure.ac and what not, but considering how trivial the fix is I'd prefer to avoid that route if possible.

**Comment by lkarsten** [comment]
As long as it is somewhat documented, rm is fine. Thanks.
