### ISSUE TITLE
Content-length not set automatically

### ISSUE THREAD

**Issue by espebra** [varnish/libvmod-curl#39]
The ``content-length`` request header is not computed and set automatically in requests when using curl from VCL. This is potentially problematic if the web server expects ``content-length`` to be set, for example with POST requests. The current workaround is manage the ``content-length`` header from VCL. 

A possibly better solution is that the content length is computed and that the header is added to the request automatically in the vmod before the request is being sent. If the ``content-length`` request header already exists, it should probably be overridden with the correct value.

**Comment by fgsch** [comment]
Are you saying that a curl.post(..) does not set the C-L? Do you have an test case?

**Comment by espebra** [comment]
Sorry I was a bit unclear, this is a corner case and I'll elaborate below.

The following works as expected, as ``content-length`` in the curl request is being calculated and set to 3:

    sub vcl_recv {
        curl.post("http://example.com/", "foo");
    }

The following works also fine, as it will not add ``content-length`` at all. This is OK since the request body is empty:

    sub vcl_recv {
        curl.set_method("POST");
        curl.get("http://example.com/");
    }

In the following example (test case attached) however, ``content-length``, if it exists in ``req``, will be copied and reused by curl:

    sub vcl_recv {
        curl.set_method(req.method);
        curl.header_add_all();
        curl.get("http://example.com");
    }

The curl request will hang if ``req.http.content-length`` is set to something larger than 0, since the web server expects curl to deliver body data that will never be sent.

It is possible to argue that ``header_add_all()`` works as intended in the way that it actually *should* copy all request headers, including ``content-length``. It is also worth noting that removing ``content-length`` before the curl request is a perfectly valid and fully functional workaround:

    sub vcl_recv {
        curl.set_method(req.method);
        curl.header_add_all();
        curl.header_remove("content-length");
        curl.get("http://example.com");
    }

However, currently I'm leaning towards that the vmod should re-calculate ``content-length``, since ``header_add_all()`` never touches the request body which ``content-length`` is derived from.

[curl-issue-39.vtc.txt](https://github.com/varnish/libvmod-curl/files/467038/curl-issue-39.vtc.txt)

**Comment by fgsch** [comment]
In principle I'm more inclined to skip C-L in header_add_all() but I will take a look.

**Comment by espebra** [comment]
Skipping ``content-length`` in ``header_add_all()`` will be a good change I believe.

**Comment by daghf** [comment]
@fgsch @espebra 

While we're at it, should we perhaps also strip Transfer-Encoding: chunked?

I imagine that would lead to a similar issue, where the web server will expect at least a terminator chunk.

**Comment by fgsch** [comment]
Indeed, we should do that too. Thanks for the cluestick!

I will do that.
