### ISSUE TITLE
Logging of request and response headers

### ISSUE THREAD

**Issue by espebra** [varnish/libvmod-curl#40]
Debugging will be easier if the vmod logs all request headers and (especially) response headers to varnishlog pr. curl request.

**Comment by daghf** [comment]
@espebra, this we can do.

Should we have something like  ``curl.do_log(true)`` which would enable automatic logging of req/resp headers to VSL, or should we rather do it explicitly via something like ``curl.log_req()`` / ``curl.log_resp()``?

**Comment by daghf** [comment]
@fgsch should I deal with this one, or are you working on it?

**Comment by espebra** [comment]
@daghf Both ``curl.do_log(true)`` and ``curl.log_req()`` / ``curl.log_resp()`` will be great solutions. I don't particularly favour one over the other.

**Comment by fgsch** [comment]
Happy to take this. I've already spent some time looking into it for
another project.

**Comment by fgsch** [comment]
Espen, should we restrict this to headers or can you foreseen any case where you want to dump the request/response body as well?
