### ISSUE TITLE
New release, libvmod-curl-1.0.4?

### ISSUE THREAD

**Issue by zstyblik** [varnish/libvmod-curl#41]
Hello,

I'm wondering whether a new release is planned. libvmod-curl-1.0.3 doesn't build against varnish-5.0.0, master branch does. However, building from master, resp. moving target is a bit, you know, meh :)

Thank you for reply and libvmod-curl :)

```
make[2]: Entering directory '/libvmod-curl'
Making all in src
make[3]: Entering directory '/libvmod-curl/src'
/usr/share/varnish/vmodtool.py ../src/vmod_curl.vcc
Traceback (most recent call last):
  File "/usr/share/varnish/vmodtool.py", line 874, in <module>
    runmain(i_vcc, opts.rstdir, opts.output)
  File "/usr/share/varnish/vmodtool.py", line 833, in runmain
    v.parse()
  File "/usr/share/varnish/vmodtool.py", line 668, in parse
    s_module(c, b[1:], self)
  File "/usr/share/varnish/vmodtool.py", line 359, in __init__
    self.parse()
  File "/usr/share/varnish/vmodtool.py", line 408, in parse
    self.vcc.moddesc = a[2]
IndexError: list index out of range
Makefile:682: recipe for target 'vcc_if.c' failed
make[3]: *** [vcc_if.c] Error 1
make[3]: Leaving directory '/libvmod-curl/src'
```

**Comment by aondio** [comment]
Hi @zstyblik,
we still haven't planned a release compatible with Varnish 5.0, is this a blocking issue for you?

**Comment by zstyblik** [comment]
Hello @aondio,

thank you for reply. We're trying to migrate to varnish 5.0 and as I've said, it would be great to have a stable point to build from instead of moving target like master branch. However, I can lock to specific commit and work-around it. No problem :)

Have a nice weekend.
