### ISSUE TITLE
varnish6.2 compile is OK but vcl not load

### ISSUE THREAD

**Issue by redbox-cdn** [varnish/libvmod-curl#51]
Hi I can not import curl in VCL. but compile seems OK. I tried varnish 5.2 is works fine on same environment (OS) . but 6.2 does not vcl load.
How should I fix issue?

```
varnishd: dlerror: /usr/local/varnish/lib/varnish/vmods/libvmod_curl.so: undefined symbol: vmod_event_function
varnishd: ('/usr/local/varnish/etc/default.vcl' Line 16 Pos 8)
varnishd: import curl;

```
Varnish6.2 Centos7

 Best regards

**Comment by daghf** [comment]
Hey @redbox-cdn 

Thanks for bringing this to our attention. Should be sorted now.

**Comment by redbox-cdn** [comment]
It works fine varnish 6.2!
