### ISSUE TITLE
Tarball has duplicated name of the directory

### ISSUE THREAD

**Issue by graywolf-at-work** [varnish/libvmod-curl#52]
Currently the directory in tarball has the `libvmod-curl` part duplicated.

```
$ tar -tf libvmod-curl-1.0.4.tar.gz | head -n1
libvmod-curl-libvmod-curl-1.0.4/
```

I think using just `libvmod-curl-1.0.4` would be sufficient.

**Comment by dridi** [comment]
Where did you fetch the archive from?

**Comment by graywolf-at-work** [comment]
https://github.com/varnish/libvmod-curl/releases
https://github.com/varnish/libvmod-curl/archive/libvmod-curl-1.0.4.tar.gz

**Comment by dridi** [comment]
Unfortunately this is a github-generated archive from the source code over which we have no control. We don't make github releases and merely tagging a release makes it appear on github.

Fortunately we provided bootstrapped archives (so you shouldn't need the autotools to build) as stated in the README:

https://download.varnish-software.com/libvmod-curl/

This should solve your problem.
