### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by FidoWue** [varnish/libvmod-curl#53]
Hi, i am the CEO from fidion in Germany. 

I need some modifications for Varnish 6.4 and https. 
Please contact me for a sponorship at schneider@fidion.de.

Best regards,
Gerhard

**Comment by gquintard** [comment]
Hi, I've pushed your request to the Varnish Software sales department, but usually we keep github issues for actionable bugs. There's also a list of companies that could provide help here: https://varnish-cache.org/business/index.html#business

**Comment by gquintard** [comment]
closing this as timed-out
