### ISSUE TITLE
Source downloads no longer available

### ISSUE THREAD

**Issue by thomersch** [varnish/libvmod-curl#54]
The readme links to https://download.varnish-software.com/libvmod-curl/ which is no longer available. Downloading from Github would be an alternative, but unfortunately the latest patches haven't got tagged yet. Are there any plans to tag a new release?

**Comment by gquintard** [comment]
hi @thomersch, this repository is mostly inactive now, so I wouldn't count on it, however, you have a couple of options:
- build directly from the git repository. Adjusting the code for Varnish 7.1 should be fairly easy
- use Varnish Enterprise (either through a [license](https://info.varnish-software.com/varnish-enterprise-us-conv) or an [AWS AMI](https://aws.amazon.com/marketplace/seller-profile?id=263c0208-6a3a-435d-8728-fa2514202fd0)), with either their maintained `vmod-curl`, or the improved [vmod-http](https://docs.varnish-software.com/varnish-cache-plus/vmods/http/)
- `<shameless plug>` Assuming you use at least Varnish 7.0, go for [vmod-reqwest](https://github.com/gquintard/vmod_reqwest), which should cover all `vmod-curl` use-cases, and if something is unclear/buggy, I'll be sure to answer any ticket you open `</shameless plug>`

**Comment by thomersch** [comment]
Ha, I got much more than I hoped for, thanks! reqwest looks excellent, I'm checking it out right now.
